### ISSUE TITLE
wrong rendering 

### ISSUE THREAD

**Issue by sonymoparthi** [notofonts/telugu#11]
wrong display

'Tiro Telugu'

<link href="https://fonts.googleapis.com/css2?family=Tiro+Telugu&display=swap" rel="stylesheet"/> 

0C1A0C48
 
<img width="870" alt="wrong one" src="https://user-images.githubusercontent.com/9820231/210399733-8442631f-e845-48a6-916b-246188ad1ee3.png">

**Comment by simoncozens** [comment]
This is the repository for Noto Sans Telugu and Noto Serif Telugu. The repository to report issues with Tiro Telugu is https://github.com/TiroTypeworks/Indigo/issues; please try there.
