### ISSUE TITLE
The subscripts in క్త్ర are clashing

### ISSUE THREAD

**Issue by sridatta1** [notofonts/telugu#12]
### Title 
The subscripts in క్త్ర are clashing
### Font 
Noto Serif and Sans Telugu

### Where the font came from, and when
  > For example:
Tested on https://fonts.google.com/
  >   Date: 2023-01-09 (preferred format)

### Application name and version
Chrome on Ubuntu
### Issue

  1. Observed results
![image](https://user-images.githubusercontent.com/23263723/211249262-768efd38-e7d1-4bd1-bd2c-320f1ff0efe6.png) 
![image](https://user-images.githubusercontent.com/23263723/211249291-c1075bf2-a940-4796-b495-fe946ca67cab.png)
 2. Expected results
![image](https://user-images.githubusercontent.com/23263723/211249336-bdec75d8-dd4a-429b-80f6-df866bff0559.png)

### Character data
క్త్ర

**Comment by sridatta1** [comment]
Some more conjuncts
ర్త్ర్య ర్త్త్ర న్త్త్ర ర్త్ర ట్త్త్ర
![image](https://user-images.githubusercontent.com/23263723/213922210-8c129a50-b6de-41f4-8264-ba415ef122f0.png)
![image](https://user-images.githubusercontent.com/23263723/213922242-d647bd63-83b2-4090-8e87-6e504d8c5981.png)

**Comment by simoncozens** [comment]
Looks like tasubscriptnarrowtelu is missing an anchor. (In fact, all the tasubscripts are missing anchors; the things which work, only work because they form `tarasubscriptligtelu` ligature glyphs.)

**Comment by simoncozens** [comment]
I've fixed this in the Sans.

**Comment by simoncozens** [comment]
And now in the serif as well.
