### ISSUE TITLE
Lots of regressions

### ISSUE THREAD

**Issue by simoncozens** [notofonts/telugu#13]
I broke ra subscript: భ్ద్ర, క్త్రో

Was:
![shape](https://user-images.githubusercontent.com/106728/220857553-5486e894-fa30-4bd8-97c5-0f6ca9826a4e.png)
Now:
![shape](https://user-images.githubusercontent.com/106728/220857661-a6130c4c-643b-4bde-8146-62ef50c1e79c.png)

I broke kerning:  కుష్నే

Was:
![shape](https://user-images.githubusercontent.com/106728/220858708-fc31bc13-d49a-47d1-808d-7429c66323bd.png)
Now:
![shape](https://user-images.githubusercontent.com/106728/220858755-b4e03dc8-7c09-425c-b12a-0653d9ac4dbd.png)

I broke spacing: నిల్వౌం

Was:
![shape](https://user-images.githubusercontent.com/106728/220858841-39160522-f4ed-49b5-91da-27e8b945d04e.png)
Now:
![shape](https://user-images.githubusercontent.com/106728/220858893-b77e2b9a-bb4c-4be1-980f-1aa76a017df1.png)

I'm sorry, this is a complete mess. We now have a much better QA system which will help us to catch this kind of thing, but I need to deploy it automatically for Noto builds.

**Comment by chrissimpkins** [comment]
Are any of the glyphs in this string involved?

```
కనెక్ట్ చేసిన పరికరం
```

**Comment by simoncozens** [comment]
I don't think so; looks fine to me:

![shape](https://user-images.githubusercontent.com/106728/221957079-f94626ac-57ff-4bc2-bb00-a27a832f4abc.png)

**Comment by simoncozens** [comment]
2.001 (MTI source) does not have this issue; 2.002 (Fea conversion) does.

**Comment by chrissimpkins** [comment]
We may need to address this in the UI builds. This is from font files that the Android team shared with me. Includes NS Telugu UI v2.003 below:

![nototelugu](https://user-images.githubusercontent.com/4249591/221979216-4300a483-ae78-4c00-995a-e6cc7493b2cb.png)

**Comment by chrissimpkins** [comment]
cc @m4rc1e

Do we understand why our diffenator font regression testing did not pick this up in the non-UI family?

**Comment by simoncozens** [comment]
Your Android issue is due to the UI *VF* build process. Here's the full story:

* Originally, we had UI and non-UI *statics*. The UI and non-UI builds for several of the Noto fonts shared the same sources (and hence the same *masters*) but differed in the *way that statics were exported*. The UI statics were generated by applying various transformations (dropping the baseline, scaling, feature replacement, glyph swapping, etc.) using Glyphs custom parameters on each instance definitions.
* Then we moved to VFs. The way that we build VFs in fontmake operates only on *masters*, and of course the UI-specific transformations were not applied to the masters, only to the instances. So when we generated "UI" VFs, we later discovered that they didn't actually have any of the UI transformations applied; they were identical to the non-UI VFs. Hence, when we moved to VFs, *we lost the ability to generate UI builds*.
* To mitigate this, Marek had me write a [VF hotfixer](https://github.com/notofonts/notobuilder/blob/main/Lib/notobuilder/builduivf.py) which looked at the Glyphs sources and the VF binary, and manually applied the custom parameters to the binary; replacing the glyphs for UI versions *in the binary* is a horrible process involving traversing the GSUB and GPOS tables and manipulating them to point at the alternate glyphs.

It's this hotfix process which is causing the problem which you are seeing. Specifically:

* In both cases, we have a buffer `katelu=0|viramatelu=0|ttatelu=0|viramatelu=0`
* In the non-UI case, the `bwlf` feature ligates virama/tta to a subscript form: `katelu=0|ttasubscripttelu=0|viramatelu=0`
* In the UI case, the `bwlf` features does the same but our VF hotfixer has (correctly) swapped out the `ttasubscripttelu` in the substitution for a `ttasubscriptUItelu`. All good so far.
* Next, the `haln` feature applies to the first `katelu` and *final* `viramatelu` *skipping the marks in between*. The marks to skip are stored in a mark attachment class definition in the GDEF table. This definition includes `ttasubscripttelu`, so in the non-UI case, this matches and `katelu|viramatelu` is substituted for a halant form `kahalanttelu`.
* The hotfix script did not modify the GDEF table (oops), so when the shaper sees `katelu|ttasubscriptUItelu| viramatelu` the `ttasubscriptUItelu` glyph is *not* skipped over, and the substitution does not match.

The proximate fix here is to make the UI VF hotfix script also do its dirty magic to the GDEF table.

I hope this goes some way to explaining why I really, *really* don't like touching the UI builds...

**Comment by m4rc1e** [comment]
@chrissimpkins I think the UI fonts predate diffenator2. I also don't see any UI prs in google/fonts itself, https://github.com/google/fonts/pulls?q=is%3Apr+telugu+is%3Aclosed

**Comment by m4rc1e** [comment]
> My understanding is that this issue refers to the non-UI family and that we pushed v2.003 to prod with these regressions via a PR on the google/fonts repository where we have had diffenator in place.

AFAIK, the v2.003 Telugu was merged 6th July 2022. First commit of diffenator2 was 22nd Aug 2022. I reckon I must have reviewed it with the original diffenator which was atrocious at picking up these shaping issues.

**Comment by chrissimpkins** [comment]
Copy that.  Thanks!

**Comment by chrissimpkins** [comment]
In a report to the Android team

![AbGSTMS9WrPrHkr](https://user-images.githubusercontent.com/4249591/222448427-0c055d02-1a86-4dd0-b4d2-fa58cc90d50a.png)

**Comment by simoncozens** [comment]
Okay. The first text is the word సెర్చ్ which is broken both in UI and non-UI builds. This is rather embarrassing for Google as the text is the word "search". The virama should be applied to the ra, skipping over the subjoiner.

The next word is నెట్వర్క్ "network", same issue with the ra and also the wa *should* subjoin the tta. (I can't reproduce that failure, however.)

The next issue another mark filtering set problem, word is "connect" కనెక్ట్ but ka + any subjoiner + virama will show it. The next text is the same problem but with a ర instead of a క. Both of these are only problems in the UI build; non-UI font is fine.

The final text, I can't quite read, but it looks like there are a couple of issues; subjoined ra not working as mentioned above, and another virama attaching to a post base instead of the consonant (mark filtering set issue).

**Comment by chrissimpkins** [comment]
Some of these look like they could be duplicates but continuing to share other images that are coming up in new issue trackers so that you have the entire picture of reported issues.

<img width="1150" alt="3cMTN2Vf48VC75e" src="https://user-images.githubusercontent.com/4249591/222530492-09c252d5-2676-49e7-bc65-7c88d7c8571d.png">

**Comment by chrissimpkins** [comment]
<img width="725" alt="3uuPsYV67zDi35E" src="https://user-images.githubusercontent.com/4249591/222530550-10a5f562-9703-498a-aa15-73b9ecba4528.png">

**Comment by simoncozens** [comment]
Some updates:

* I fixed subscript ra (భ్ద్ర); two lookups had been combined into one, and this was causing some substitutions not to fire.
* Halant forms not forming with subscripts (సెర్చ్) - and possibly many of the more recent (nonUI) issues: this was a [glyphsLib bug](https://github.com/googlefonts/glyphsLib/issues/764)! Oddly, I already fixed the bug in a completely unrelated context, but that hasn't made it into a glyphsLib release yet. So when glyphsLib is released, most of this issue will magically get fixed.
* The kerning is difficult one. I'm not sure if it's even possible to fix this in our current fontmake workflow. This is because ufo2ft kerns bases against bases ignoring marks, but we make use of *spacing* marks.  In "కుషే" "కషే" we want to insert a kern between the second pair (కషే ) to stop the two above marks banging into each other. But when we have "కుషే" we don't need a kern. And if the vowel sign "ు" was a base, we wouldn't get a kern; but because it's a mark, it gets skipped over and the kern is applied.
* The "spacing" issue is the same thing. We probably need a way to tell the kern feature writer *not* to skip marks, since we are using spacing mark glyphs so heavily as we make layout decisions.

**Comment by simoncozens** [comment]
* The second part of the ra subscript problem (క్త్రో) is the same bug as #12, so I'm going to ignore it here and fix it over there.
* I fixed the kerning issue in [ufo2ft](https://github.com/googlefonts/ufo2ft/pull/720), but it will require merging and a new release and so on.
* That leaves the UI issues (hats of క and ర not getting cut off when virama applied to post-base conjunct forms). I'm going to open that in a new issue, and then everything here is resolved.

(Modulo glyphsLib/ufo2ft updates.)

**Comment by simoncozens** [comment]
Note to self: if ra-subscript starts failing inexplicably, before fiddling with the feature code (which is fine) ensure you have the latest glyphsLib and ufo2ft.
