### ISSUE TITLE
Bugs in Telugu font at OS level in Android.

### ISSUE THREAD

**Issue by neogitter** [notofonts/telugu#2]
I would like to bring to your notice about the bugs in Telugu language at OS level.
1. The AM and PM suffixed in time fields are unusually having brackets across the OS [AM] Other indic languages do not have the same issue. Please remove the [ ] from Telugu language at OS level as this is reproduced in all the apps. Also we use Month Date, Day format. జూన్ 25, శనివారం. This seems to be correctly presented in Malayalam but is sown as Day, Month Date in Telugu. So please fix this across the OS too.
2. We do not use "&" in Indic languages. Each indic language has its own term for '&'. In telugu we use "మరియు". Please implement this across the OS for Telugu language.
3. The baseline and top line for Telugu, English and numericals are not adjusted properly and hence at places like messaging apps where the line spacing is adjusted only for English language, many alphabets and conjuncts of Telugu words are being abruptly cut off, giving a tough time for the users to comprehend the meanings of those cut off words. Please adjust the font size of Telugu so that English, Telugu and numericals all stay relatively at the same baseline.

![screenshot_20160625-115554](https://cloud.githubusercontent.com/assets/20138287/16355466/fb19024c-3ad4-11e6-8649-a2a778923fa5.png)
![screenshot_20160625-121343](https://cloud.githubusercontent.com/assets/20138287/16355467/0027cbb0-3ad5-11e6-8792-b0865246f0ea.png)
![screenshot_20160625-115633](https://cloud.githubusercontent.com/assets/20138287/16355468/040a3fba-3ad5-11e6-9b7d-3d2686e10702.png)
![screenshot_20160625-121140](https://cloud.githubusercontent.com/assets/20138287/16355469/07aacf7c-3ad5-11e6-943c-884bec143eef.png)
![download_20160624_222326](https://cloud.githubusercontent.com/assets/20138287/16355470/0b6b163a-3ad5-11e6-9e6f-997cce1980e1.jpg)

**Comment by SKing-2003** [comment]
The only remaining bug in this issue seems to be the baseline issue, at #1
