### ISSUE TITLE
NotoSansTelugu font is not working in iOS 15 and 16 version

### ISSUE THREAD

**Issue by swarna456** [notofonts/telugu#23]
Steps to reproduce the issue:

Install the app and select telugu language and click on apply then next page will come. Verify it the data is correct.
Kill the app and relaunch it again select the telugu and apply. You'll see some the text is incorrect.
In this Sample project, the text is rendering properly at first launch and after killing the app and relaunching then it's not rendering properly(showing text incorrect). But in my older project it's working as vice versa(the text is not rendering properly but in console it's showing correct text at first launch and after killing the app and relaunching then it's working). But issue is same. Text is not coming correctly. For reference you can check the code and screenshot also. Thank you in advance!

Git repo:

[fontIssue.git](https://github.com/swarna456/fontIssue.git)

Screenshot:

**Correct text:** 
<img width="197" alt="correct_text" src="https://github.com/notofonts/telugu/assets/107610114/8d27d4b7-0dea-4a5c-9aa2-08d72d3c39c5">

![](https://i.stack.imgur.com/nfHO2.png)

**Incorrect image:**
![](https://i.stack.imgur.com/D5rRc.png)

**Comment by simoncozens** [comment]
If the font is working correctly the first time, then it seems more likely to be a bug in Apple's rendering software than in the font.
