### ISSUE TITLE
Android UI VF issues

### ISSUE THREAD

**Issue by simoncozens** [notofonts/telugu#9]
Android requires a "UI build" of Noto Sans Telugu, delivered as a slim variable font. We can't currently build the UI VFs from the Glyphs sources directly - the UI styles is defined as a set of instances with various magical custom parameters to re-encode glyphs, replace features, and transform the glyph outlines. We do have a way to hotfix the ordinary VF into the UI VF, but it's a horrible (and manual) process.

The process needs to become more robust, automated, and tested. Current issues on the previous build:

1) Name tables need updating
2) I ran the hotfixer on the full-range VF instead of the slim VF.

**Comment by simoncozens** [comment]
Development CI build: https://notofonts.github.io/telugu/fonts/NotoSansTelugu/unhinted/slim-variable-ttf/NotoSansTelugu-UI-VF.ttf

**Comment by chrissimpkins** [comment]
Fixed. Thank you very much Simon
